const RegionesYcomunas = {
    "regiones": [
        {
            "NombreRegion": "Región de Tarapacá",
            "idRegion": "1",
            "comunas": [
                "Camiña",
                "Huara",
                "Pozo Almonte",
                "Iquique",
                "Pica",
                "Colchane",
                "Alto Hospicio"
            ],
            "idComunas": [
                "10301",
                "10302",
                "10303",
                "10304",
                "10305",
                "10306",
                "10307"
            ]
        },
        {
            "NombreRegion": "Región de Antofagasta",
            "idRegion": "2",
            "comunas": [
                "Tocopilla",
                "Maria Elena",
                "Ollague",
                "Calama",
                "San Pedro Atacama",
                "Sierra Gorda",
                "Mejillones",
                "Antofagasta",
                "Taltal"
            ],
            "idComunas": [
                "20101",
                "20102",
                "20201",
                "20202",
                "20203",
                "20301",
                "20302",
                "20303",
                "20304"
            ]
        },
        {
            "NombreRegion": "Región de Atacama",
            "idRegion": "3",
            "comunas": [
                "Diego de Almagro",
                "Chañaral",
                "Caldera",
                "Copiapo",
                "Tierra Amarilla",
                "Huasco",
                "Freirina",
                "Vallenar",
                "Alto del Carmen"
            ],
            "idComunas": [
                "30101",
                "30102",
                "30201",
                "30202",
                "30203",
                "30301",
                "30302",
                "30303",
                "30304"
            ]
        },
        {
            "NombreRegion": "Región de Coquimbo ",
            "idRegion": "4",
            "comunas": [
                "La Higuera",
                "La Serena",
                "Vicuña",
                "Paihuano",
                "Coquimbo",
                "Andacollo",
                "Rio Hurtado",
                "Ovalle",
                "Monte Patria",
                "Punitaqui",
                "Combarbala",
                "Mincha",
                "Illapel",
                "Salamanca",
                "Los Vilos"
            ],
            "idComunas": [
                "40101",
                "40102",
                "40103",
                "40104",
                "40105",
                "40106",
                "40201",
                "40202",
                "40203",
                "40204",
                "40205",
                "40301",
                "40302",
                "40303",
                "40304"
            ]
        },
        {
            "NombreRegion": "Región de Valparaíso",
            "idRegion": "5",
            "comunas": [
                "Petorca",
                "Cabildo",
                "Papudo",
                "La Ligua",
                "Zapallar",
                "Putaendo",
                "Santa Maria",
                "San Felipe",
                "Pencahue",
                "Catemu",
                "Llay Llay",
                "Nogales",
                "La Calera",
                "Hijuelas",
                "La Cruz",
                "Quillota",
                "Olmue",
                "Limache",
                "Los Andes",
                "Rinconada",
                "Calle Larga",
                "San Esteban",
                "Puchuncavi",
                "Quintero",
                "Viña del Mar",
                "Villa Alemana",
                "Quilpue",
                "Valparaiso",
                "Juan Fernandez",
                "Casablanca",
                "Concon",
                "Isla de Pascua",
                "Algarrobo",
                "El Quisco",
                "El Tabo",
                "Cartagena",
                "San Antonio",
                "Santo Domingo"
            ],
            "idComunas": [
                "50101",
                "50102",
                "50103",
                "50104",
                "50105",
                "50201",
                "50202",
                "50203",
                "50204",
                "50205",
                "50206",
                "50301",
                "50302",
                "50303",
                "50304",
                "50305",
                "50306",
                "50307",
                "50401",
                "50402",
                "50403",
                "50404",
                "50501",
                "50502",
                "50503",
                "50504",
                "50505",
                "50506",
                "50507",
                "50508",
                "50509",
                "50601",
                "50701",
                "50702",
                "50703",
                "50704",
                "50705",
                "50706"
            ]
        },
        {
            "NombreRegion": "Región del Libertador Bernardo Ohiggins",
            "idRegion": "6",
            "comunas": [
                "Mostazal",
                "Codegua",
                "Graneros",
                "Machali",
                "Rancagua",
                "Olivar",
                "Doñihue",
                "Requinoa",
                "Coinco",
                "Coltauco",
                "Quinta Tilcoco",
                "Las Cabras",
                "Rengo",
                "Peumo",
                "Pichidegua",
                "Malloa",
                "San Vicente",
                "Navidad",
                "La Estrella",
                "Marchigue",
                "Pichilemu",
                "Litueche",
                "Paredones",
                "San Fernando",
                "Peralillo",
                "Placilla",
                "Chimbarongo",
                "Palmilla",
                "Nancagua",
                "Santa Cruz",
                "Pumanque",
                "Chepica",
                "Lolol"
            ],
            "idComunas": [
                "60101",
                "60102",
                "60103",
                "60104",
                "60105",
                "60106",
                "60107",
                "60108",
                "60109",
                "60110",
                "60111",
                "60112",
                "60113",
                "60114",
                "60115",
                "60116",
                "60117",
                "60201",
                "60202",
                "60203",
                "60204",
                "60205",
                "60206",
                "60301",
                "60302",
                "60303",
                "60304",
                "60305",
                "60306",
                "60307",
                "60308",
                "60309",
                "60310"
            ]
        },
        {
            "NombreRegion": "Región del Maule",
            "idRegion": "7",
            "comunas": [
                "Teno",
                "Romeral",
                "Rauco",
                "Curico",
                "Sagrada Familia",
                "Hualañe",
                "Vichuquen",
                "Molina",
                "Licanten",
                "Rio Claro",
                "Curepto",
                "Pelarco",
                "Talca",
                "Pencahue",
                "San Clemente",
                "Constitucion",
                "Maule",
                "Empedrado",
                "San Rafael",
                "San Javier",
                "Colbun",
                "Villa Alegre",
                "Yerbas Buenas",
                "Linares",
                "Longavi",
                "Retiro",
                "Parral",
                "Chanco",
                "Pelluhue",
                "Cauquenes"
            ],
            "idComunas": [
                "70101",
                "70102",
                "70103",
                "70104",
                "70105",
                "70106",
                "70107",
                "70108",
                "70109",
                "70201",
                "70202",
                "70203",
                "70204",
                "70205",
                "70206",
                "70207",
                "70208",
                "70209",
                "70210",
                "70301",
                "70302",
                "70303",
                "70304",
                "70305",
                "70306",
                "70307",
                "70308",
                "70401",
                "70402",
                "70403"
            ]
        },
        {
            "NombreRegion": "Región del Biobío",
            "idRegion": "8",
            "comunas": [
                "Tome",
                "Florida",
                "Penco",
                "Talcahuano",
                "Concepcion",
                "Hualqui",
                "Coronel",
                "Lota",
                "Santa Juana",
                "Chiguayante",
                "San Pedro de la Paz",
                "Hualpen",
                "Cabrero",
                "Yumbel",
                "Tucapel",
                "Antuco",
                "San Rosendo",
                "Laja",
                "Quilleco",
                "Los Angeles",
                "Nacimiento",
                "Negrete",
                "Santa Barbara",
                "Quilaco",
                "Mulchen",
                "Alto Bio Bio",
                "Arauco",
                "Curanilahue",
                "Los Alamos",
                "Lebu",
                "Cañete",
                "Contulmo",
                "Tirua"
            ],
            "idComunas": [
                "80201",
                "80202",
                "80203",
                "80204",
                "80205",
                "80206",
                "80207",
                "80208",
                "80209",
                "80210",
                "80211",
                "80212",
                "80301",
                "80302",
                "80303",
                "80304",
                "80305",
                "80306",
                "80307",
                "80308",
                "80309",
                "80310",
                "80311",
                "80312",
                "80313",
                "80314",
                "80401",
                "80402",
                "80403",
                "80404",
                "80405",
                "80406",
                "80407"
            ]
        },
        {
            "NombreRegion": "Región de La Araucanía",
            "idRegion": "9",
            "comunas": [
                "Renaico",
                "Angol",
                "Collipulli",
                "Los Sauces",
                "Puren",
                "Ercilla",
                "Lumaco",
                "Victoria",
                "Traiguen",
                "Curacautin",
                "Lonquimay",
                "Perquenco",
                "Galvarino",
                "Lautaro",
                "Vilcun",
                "Temuco",
                "Carahue",
                "Melipeuco",
                "Nueva Imperial",
                "Puerto Saavedra",
                "Cunco",
                "Freire",
                "Pitrufquen",
                "Teodoro Schmidt",
                "Gorbea",
                "Pucon",
                "Villarrica",
                "Tolten",
                "Curarrehue",
                "Loncoche",
                "Padre Las Casas",
                "Cholchol"
            ],
            "idComunas": [
                "90101",
                "90102",
                "90103",
                "90104",
                "90105",
                "90106",
                "90107",
                "90108",
                "90109",
                "90110",
                "90111",
                "90201",
                "90202",
                "90203",
                "90204",
                "90205",
                "90206",
                "90207",
                "90208",
                "90209",
                "90210",
                "90211",
                "90212",
                "90213",
                "90214",
                "90215",
                "90216",
                "90217",
                "90218",
                "90219",
                "90220",
                "90221"
            ]
        },
        {
            "NombreRegion": "Región de Los Lagos",
            "idRegion": "10",
            "comunas": [
                "San Pablo",
                "San Juan",
                "Osorno",
                "Puyehue",
                "Rio Negro",
                "Purranque",
                "Puerto Octay",
                "Frutillar",
                "Fresia",
                "Llanquihue",
                "Puerto Varas",
                "Los Muermos",
                "Puerto Montt",
                "Maullin",
                "Calbuco",
                "Cochamo",
                "Ancud",
                "Quemchi",
                "Dalcahue",
                "Curaco de Velez",
                "Castro",
                "Chonchi",
                "Queilen",
                "Quellon",
                "Quinchao",
                "Puqueldon",
                "Chaiten",
                "Futaleufu",
                "Palena",
                "Hualaihue"
            ],
            "idComunas": [
                "100201",
                "100202",
                "100203",
                "100204",
                "100205",
                "100206",
                "100207",
                "100301",
                "100302",
                "100303",
                "100304",
                "100305",
                "100306",
                "100307",
                "100308",
                "100309",
                "100401",
                "100402",
                "100403",
                "100404",
                "100405",
                "100406",
                "100407",
                "100408",
                "100409",
                "100410",
                "100501",
                "100502",
                "100503",
                "100504"
            ]
        },
        {
            "NombreRegion": "Región Aisén del General Carlos Ibáñez del Campo",
            "idRegion": "11",
            "comunas": [
                "Guaitecas",
                "Cisnes",
                "Aysen",
                "Coyhaique",
                "Lago Verde",
                "Rio Iba?ez",
                "Chile Chico",
                "Cochrane",
                "Tortel",
                "O''Higins"
            ],
            "idComunas": [
                "110101",
                "110102",
                "110103",
                "110201",
                "110202",
                "110301",
                "110302",
                "110401",
                "110402",
                "110403"
            ]
        },
        {
            "NombreRegion": "Región de Magallanes y la Antártica Chilena",
            "idRegion": "12",
            "comunas": [
                "Torres del Paine",
                "Puerto Natales",
                "Laguna Blanca",
                "San Gregorio",
                "Rio Verde",
                "Punta Arenas",
                "Porvenir",
                "Primavera",
                "Timaukel",
                "Antartica"
            ],
            "idComunas": [
                "120101",
                "120102",
                "120201",
                "120202",
                "120203",
                "120204",
                "120301",
                "120302",
                "120303",
                "120401"
            ]
        },
        {
            "NombreRegion": "Región Metropolitana de Santiago ",
            "idRegion": "13",
            "comunas": [
                "Tiltil",
                "Colina",
                "Lampa",
                "Conchali",
                "Quilicura",
                "Renca",
                "Las Condes",
                "Pudahuel",
                "Quinta Normal",
                "Providencia",
                "Santiago",
                "La Reina",
                "Ñuñoa",
                "San Miguel",
                "Maipu",
                "La Cisterna",
                "La Florida",
                "La Granja",
                "Independencia",
                "Huechuraba",
                "Recoleta",
                "Vitacura",
                "Lo Barrenechea",
                "Macul",
                "Peñalolen",
                "San Joaquin",
                "La Pintana",
                "San Ramon",
                "El Bosque",
                "Pedro Aguirre Cerda",
                "Lo Espejo",
                "Estacion Central",
                "Cerrillos",
                "Lo Prado",
                "Cerro Navia",
                "San Jose de Maipo",
                "Puente Alto",
                "Pirque",
                "San Bernardo",
                "Calera de Tango",
                "Buin",
                "Paine",
                "Peñaflor",
                "Talagante",
                "El Monte",
                "Isla de Maipo",
                "Curacavi",
                "Maria Pinto",
                "Melipilla",
                "San Pedro",
                "Alhue",
                "Padre Hurtado"
            ],
            "idComunas": [
                "130101",
                "130102",
                "130103",
                "130201",
                "130202",
                "130203",
                "130204",
                "130205",
                "130206",
                "130207",
                "130208",
                "130209",
                "130210",
                "130211",
                "130212",
                "130213",
                "130214",
                "130215",
                "130216",
                "130217",
                "130218",
                "130219",
                "130220",
                "130221",
                "130222",
                "130223",
                "130224",
                "130225",
                "130226",
                "130227",
                "130228",
                "130229",
                "130230",
                "130231",
                "130232",
                "130301",
                "130302",
                "130303",
                "130401",
                "130402",
                "130403",
                "130404",
                "130501",
                "130502",
                "130503",
                "130504",
                "130601",
                "130602",
                "130603",
                "130604",
                "130605",
                "130606"
            ]
        },
        {
            "NombreRegion": "Región de Los Ríos",
            "idRegion": "14",
            "comunas": [
                "Lanco",
                "Mariquina",
                "Panguipulli",
                "Mafil",
                "Valdivia",
                "Los Lagos",
                "Corral",
                "Paillaco",
                "Futrono",
                "Lago Ranco",
                "La Union",
                "Rio Bueno"
            ],
            "idComunas": [
                "100101",
                "100102",
                "100103",
                "100104",
                "100105",
                "100106",
                "100107",
                "100108",
                "100109",
                "100110",
                "100111",
                "100112"
            ]
        },
        {
            "NombreRegion": "Región Arica y Parinacota",
            "idRegion": "15",
            "comunas": [
                "Gral. Lagos",
                "Putre",
                "Arica",
                "Camarones"
            ],
            "idComunas": [
                "10101",
                "10102",
                "10201",
                "10202"
            ]
        },
        {
            "NombreRegion": "Región del Ñuble",
            "idRegion": "16",
            "comunas": [
                "Cobquecura",
                "Ñiquen",
                "San Fabian",
                "San Carlos",
                "Quirihue",
                "Ninhue",
                "Trehuaco",
                "San Nicolas",
                "Coihueco",
                "Chillan",
                "Portezuelo",
                "Pinto",
                "Coelemu",
                "Bulnes",
                "San Ignacio",
                "Ranquil",
                "Quillon",
                "El Carmen",
                "Pemuco",
                "Yungay",
                "Chillan Viejo"
            ],
            "idComunas": [
                "80101",
                "80102",
                "80103",
                "80104",
                "80105",
                "80106",
                "80107",
                "80108",
                "80109",
                "80110",
                "80111",
                "80112",
                "80113",
                "80114",
                "80115",
                "80116",
                "80117",
                "80118",
                "80119",
                "80120",
                "80121"
            ]
        }
    ]
}

jQuery(document).ready(function () {

	let iRegion = 0;
	let htmlRegion = '<option value="">Seleccione región</option><option value="sin-region">--</option>';
	const htmlComunas = '<option value="">Seleccione comuna</option><option value="sin-region">--</option>';

	jQuery.each(RegionesYcomunas.regiones, function () {
		htmlRegion = htmlRegion + '<option value="' + RegionesYcomunas.regiones[iRegion].idRegion + '">' + RegionesYcomunas.regiones[iRegion].NombreRegion + '</option>';
		iRegion++;
	});

	jQuery('#region').html(htmlRegion);
	jQuery('#comuna').html(htmlComunas);

	jQuery('#region').change(function () {
		let iRegiones = 0;
		const valorRegion = jQuery(this).val();
		let htmlComuna = '<option value="">Seleccione comuna</option><option value="sin-comuna">--</option>';
		jQuery.each(RegionesYcomunas.regiones, function () {
			if (RegionesYcomunas.regiones[iRegiones].idRegion === valorRegion) {
				let iComunas = 0;
				jQuery.each(RegionesYcomunas.regiones[iRegiones].comunas, function () {
					htmlComuna = htmlComuna + '<option value="' + RegionesYcomunas.regiones[iRegiones].idComunas[iComunas] + '">' + RegionesYcomunas.regiones[iRegiones].comunas[iComunas] + '</option>';
					iComunas++;
				});
			}
			iRegiones++;
		});
		jQuery('#comuna').html(htmlComuna);
	});
	jQuery('#comuna').change(function () {
		if (jQuery(this).val() === 'sin-region') {
			alert('selecciones Región');
		} else if (jQuery(this).val() === 'sin-comuna') {
			alert('Selecciona una Comuna');
		}
	});
	jQuery('#region').change(function () {
		if (jQuery(this).val() === 'sin-region') {
			alert('Selecciona una Región');
		}
	});

});